class Names:
    Commoner = [
        "Wilbur",
        "Martha",
        "Ernest",
        "Mary",
        "Bob",
        "Betty",
        "Jeremy",
        "Maggie",
        "Billy",
        "Sara",
        "Crispin",
        "Lucy",
        "Dudley",
        "Annie",
        "Gilbert",
        "Maude",
        "Hubert",
        "Wilma",
        "John",
        "Jane",
        "Tim",
        "Pam",
        "Jim",
        "Angela",
        "Ted",
        "Bella",
        "Andy",
        "Karen",
        "Mike",
        "Kathy",
        "George",
        "Emma",
        "Trent",
        "Pat",
        "Ralph",
        "Athelflad",
        "Unferth",
        "Ethel",
        "Bart",
        "Hilda",
        "Dunstan",
        "Agnes",
        "Stanley",
        "Mildred"
    ]

    Noble = [
        "Galahad",
        "Sieglinde",
        "Hector",
        "Isabella",
        "Ephraim",
        "Josephine",
        "Alaric",
        "Annora",
        "Florian",
        "Catherine",
        "Godwin",
        "Celestina",
        "Leoric",
        "Minerva",
        "Arthur",
        "Lucia",
        "Osric",
        "Liliana",
        "Thorin",
        "Cleopatra",
        "Geraldus",
        "Guinevere",
        "Ealdraed",
        "Elizabeth",
        "Percival"
    ]

    Mage = [
        "Algernon",
        "Ophelia",
        "Archibald",
        "Euphemia",
        "Merlin",
        "Morrigan",
        "Ozymandias",
        "Persephone",
        "Arcturus",
        "Freya",
        "Artemis",
        "Beatrix",
        "Tiberius",
        "Zara",
        "Zephyr",
        "Seraphina",
        "Atticus",
        "Selene",
        "Peregrine",
        "Andromeda"
    ]

class Titles:
    Peasant = [
        "Baker",
        "Miller",
        "Meek",
        "Farmer",
        "Woodcutter",
        "Tanner",
        "Blacksmith",
        "Frail",
        "Beggar",
        "Cobbler",
        "Fisher",
        "Haberdasher",
        "Grocer",
        "Unwashed",
        "Overlooked",
        "Carpenter",
        "Weaver",
        "Minstrel",
        "Goatherd",
        "Candlemaker",
        "Stonemason",
        "Unreliable",
        "Gardener",
        "Winemaker",
        "Wheelright",
        "Locksmith",
        "Birdcatcher",
        "Tavern Keeper"
    ]

    Soldier = [
        "Vigilant",
        "Stout",
        "Sturdy",
        "Protector",
        "Grim",
        "One-Eyed",
        "Ox",
        "Brawny",
        "Steadfast",
        "Fierce",
        "Tenacious",
        "Veteran",
        "Mercenary",
        "Sellsword",
        "Gruff",
        "Stoic",
        "Unwavering",
        "Loyal",
        "Dependable",
        "Stalwart",
        "Unflinching",
        "Surly",
        "Churlish",
        "Taciturn"
    ]

    Archer = [
        "Swift",
        "Unerring",
        "Nimble",
        "Eagle-Eyed",
        "Shrewd",
        "Careful",
        "Quick",
        "Deadshot",
        "Reliable",
        "Scout",
        "Ranger",
        "Marksman",
        "Hunter",
        "Skirmisher",
        "Sniper"
    ]

    Cavalry = [
        "Brave",
        "True",
        "Bold",
        "Just",
        "Fierce",
        "Unbroken",
        "Lionhearted",
        "Oathbound",
        "Gallant",
        "Bulwark",
        "Mighty",
        "Resolute",
        "Paladin"
    ]

    Sorcerer = [
        "Enchanter",
        "Warlock",
        "Seer",
        "Conjurer",
        "Mystical",
        "Black",
        "Magician",
        "Evoker",
        "Theurgist",
        "Trickster",
        "Sage",
        "Mage"
    ]

    Healer = [
        "Gentle",
        "Savior",
        "Guardian",
        "Guiding Light",
        "Beacon of Hope",
        "Lightbringer",
        "Prophet",
        "High Priest",
        "Druid",
        "Soulmender",
        "Dawnlight"
    ]

    Archmage = [
        "Wise",
        "Destroyer",
        "Unfathomable",
        "Supreme",
        "Fatetwister",
        "Skybreaker",
        "All-Seeing",
        "Eternal",
        "High Magus",
        "Soul-Flayer",
        "Void-Bringer",
        "Earth-Render"
    ]

    General = [
        "Conqueror",
        "Great",
        "Glorious",
        "Dragonslayer",
        "Unstoppable",
        "Unifier",
        "Champion"
    ]